---
# tasks file for apigee-opdk-setup-apigee-user-ownership
- name: Installation home stats
  stat:
    path: '{{ apigee_home }}'
  register: apigee_home_status

- name: Setup permission for apigee installation home directory
  become: yes
  file:
    path: '{{ apigee_home }}'
    group: '{{ opdk_group_name }}'
    owner: '{{ opdk_user_name }}'
    mode: 0755
    recurse: yes
    state: directory
  when: not apigee_home_status.stat.exists


